[firebase]
type = "service_account"
project_id = "cvv-smartexam-v2"
private_key_id = "b78822075411129abebb8f393be39ed5a2cb91d6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrd3sBFYBAp7Dg
l8Bl/3G9tU20bxhy9+IQpxphVf8+1+P5rlpL+KDvCd28F5e2vyNO+54B7ky4XHDL
9aK6i4h27E6CuW4J+GH11Wh4/M8xkRk11qiVfECUUOkHkiFR5K+AZPKh3bOzp0QR
Ue7QZoV7LkHbt0t7iyNxq0NsQ4Np5DmtQP+dWuRImCtPZyhykDi3+/KyfwDRqh9X
UeHl71Mu30P7n4+fsh+sMPnO/Um9QPJ99uR2V0seTDToaMhZZEm6BjtzPqk6yMbk
aXYmV7Mr1uXEuXaiXGA1bJfUKn9k107Ahgvszxjx3BTEXGw34/a6qCSE7CgpEv3b
unbwCdrRAgMBAAECggEACS0cPiP/Q0TA0JNJIj4Llr3cOjgpYNqccQx73otUQKrG
iw44BMNdlJY1hubki+kxg7X2vmYK/ZolTolx6bWzKGfm9NQeLA9sW40jQo7AHk89
TlDovNpeRiqW/uABNUQIaCtbSlXEjJcI1jw7Gm19s8wTxk/mt2ZeAYEgk/nVpNmD
mqx9E7dPM+pRFqUVBPRugksBCEwxvWMY3Y+m3ifpdos4fFryHee5cZZ4g6xV2bAe
8c/AzWAHl0WbEEifJl+Z4MJ1a5RNXud37wJCIpA+v3QN7PanQv/tIHE3Ee56VtpC
XB3c1xE+hhehsyWyaN6n1ey/x6BEdxJymv3IqRppdwKBgQDfCOpjvECy1dzryw80
TT/4L0ZfDeYGPnAUDN2pCf0b8OiaesS5as3XMMKl6ajIELfmqxbJbKAJEiRTUKQN
e2HS1bDIpBmb62uDeiZOMwttzhk3hQuSEOsq8cb1Gk1HbxmLhim+NjJKKtPSbI7W
CWqn2arMOClIPMY/6K0ztaserwKBgQDEz1sRQBBbgc+PRD61AoQ7hIosBKlf7vns
XATtlTjBzXiKG4pDxeZtWB0TvxXsTuTY3VsAi4S33Ij3oc60yPUsggn0V1qr8OnV
8kNdUeMMPX9TpCREl8uBSTOq01Bym8S873rUQ+zbJz1INegAT0yCUMPl7pMwSzwv
NB6IwIz+fwKBgQDHRvQGAOHd5+/oThpbpNoPKk46B/UKhyclAwnaSy53lJx/ykmT
UbZxGwQPseI4P5fQ5fUKK6Ah+q+yMU8jLKaO9pdp7hVjlskNREqNfFYt2gP1804P
SEaWrEgUH1gFB2NPoqQRa+MrGXEBhjVpUCiXqIhOx6869/I6j+6RUTR/yQKBgHzJ
xUJQzo5W5pY+fUwkRle+mCWE5ygOzKTTS8SgwxYPBAj9oVOLnaljHzywAmSNOYlQ
AS19SS+TQ71P+VKjwODxqwIkiTdQT9P6AkCfdUkDjUIpZ12eqchV886yoeWpYrsx
VT5Vu07RuIeatnnLzgUq1Ktr9CPA8G41q86l2EBdAoGAdo0Y+V1Q7hf/VuBA7jx8
y8P8+S1SouWfIYDsG//99Rul3NCG3Zh5KtvmKbe3EfvUwxc1nRNKsTHMazDwCK2d
z7PT7+zHljOijxcWnHsaioVVDnZddXpXRayuyPpj5eIEzcRrvJD2JFv8e8HJvQBR
CiNnadO4xKesB1HAzv06Kps=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@cvv-smartexam-v2.iam.gserviceaccount.com"
client_id = "112980992524115194629"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40cvv-smartexam-v2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"